version: '3'

services:

    crawler:
    
      build: .

      container_name: naver_land_crawler

      image: naver_land_crawler:latest
    
      command: bash -c "scrapy crawl RegionSpider && scrapy crawl NaverLandSpider"

      ports:
        - "7000:7000"

      
    db:

      image: mysql:8.0.28

      container_name: mysqlserver

      ports:
        - '3307:3306'
      
      restart: always

      environment:
        LC_ALL: C.UTF-8
        TZ: Asia/Seoul

        
      volumes:
        - ~/NaverLand/data/mysql:/var/lib/mysql

      
